# ant example
file(GLOB ANT_SRC  "${CMAKE_CURRENT_SOURCE_DIR}/src/Beagle-Examples/ant/*.cpp")
file(GLOB ANT_DATA "${CMAKE_CURRENT_SOURCE_DIR}/src/Beagle-Examples/ant/*.conf" "${CMAKE_CURRENT_SOURCE_DIR}/examples/ant/*.xml" "${CMAKE_CURRENT_SOURCE_DIR}/src/Beagle-Examples/ant/*.trail" "${CMAKE_CURRENT_SOURCE_DIR}/src/Beagle-Examples/ant/ReadMe.txt")
add_executable(ant ${ANT_SRC})
add_dependencies(ant Beagle-GP Beagle-EC Beagle-Core)
target_link_libraries(ant Beagle-GP Beagle-EC Beagle-Core pacc)
set_target_properties(ant PROPERTIES RUNTIME_OUTPUT_DIRECTORY "${BEAGLE_OUTPUT_DIR}/bin/ant")
MoveConfigFiles("${ANT_DATA}" "${BEAGLE_OUTPUT_DIR}/bin/ant" false)
install(TARGETS ant DESTINATION bin/ant)
install(FILES ${ANT_DATA} DESTINATION bin/ant)

# knapsack example
file(GLOB KNAPSACK_SRC  "${CMAKE_CURRENT_SOURCE_DIR}/src/Beagle-Examples/knapsack/*.cpp")
file(GLOB KNAPSACK_DATA "${CMAKE_CURRENT_SOURCE_DIR}/src/Beagle-Examples/knapsack/*.conf" "${CMAKE_CURRENT_SOURCE_DIR}/src/Beagle-Examples/knapsack/ReadMe.txt")
add_executable(knapsack ${KNAPSACK_SRC})
add_dependencies(knapsack Beagle-EMO Beagle-BitStr Beagle-EC Beagle-Core)
target_link_libraries(knapsack Beagle-EMO Beagle-BitStr Beagle-EC Beagle-Core pacc)
set_target_properties(knapsack PROPERTIES RUNTIME_OUTPUT_DIRECTORY "${BEAGLE_OUTPUT_DIR}/bin/knapsack")
MoveConfigFiles("${KNAPSACK_DATA}" "${BEAGLE_OUTPUT_DIR}/bin/knapsack" false)
install(TARGETS knapsack DESTINATION bin/knapsack)
install(FILES ${KNAPSACK_DATA} DESTINATION bin/knapsack)

# knapsack-hpc example
if(NOT BEAGLE_NO_HPC)
    file(GLOB KNAPSACK_HPC_SRC  "${CMAKE_CURRENT_SOURCE_DIR}/src/Beagle-Examples/knapsack-hpc/*.cpp")
    file(GLOB KNAPSACK_HPC_DATA "${CMAKE_CURRENT_SOURCE_DIR}/src/Beagle-Examples/knapsack-hpc/*.conf")
    add_executable(knapsack-hpc ${KNAPSACK_HPC_SRC})
    add_dependencies(knapsack-hpc Beagle-HPC Beagle-EMO Beagle-BitStr Beagle-EC Beagle-Core)
    target_link_libraries(knapsack-hpc Beagle-HPC Beagle-EMO Beagle-BitStr Beagle-EC Beagle-Core pacc)
    set_target_properties(knapsack-hpc PROPERTIES RUNTIME_OUTPUT_DIRECTORY "${BEAGLE_OUTPUT_DIR}/bin/knapsack-hpc")
    MoveConfigFiles("${KNAPSACK_HPC_DATA}" "${BEAGLE_OUTPUT_DIR}/bin/knapsack-hpc" false)
    install(TARGETS knapsack-hpc DESTINATION bin/knapsack-hpc)
    install(FILES ${KNAPSACK_HPC_DATA} DESTINATION bin/knapsack-hpc)
endif(NOT BEAGLE_NO_HPC)

# maxfct example
file(GLOB MAXFCT_SRC  "${CMAKE_CURRENT_SOURCE_DIR}/src/Beagle-Examples/maxfct/*.cpp")
file(GLOB MAXFCT_DATA "${CMAKE_CURRENT_SOURCE_DIR}/src/Beagle-Examples/maxfct/*.conf" "${CMAKE_CURRENT_SOURCE_DIR}/src/Beagle-Examples/maxfct/ReadMe.txt")
add_executable(maxfct ${MAXFCT_SRC})
add_dependencies(maxfct Beagle-BitStr Beagle-EC Beagle-Core)
target_link_libraries(maxfct Beagle-BitStr Beagle-EC Beagle-Core pacc)
set_target_properties(maxfct PROPERTIES RUNTIME_OUTPUT_DIRECTORY "${BEAGLE_OUTPUT_DIR}/bin/maxfct")
MoveConfigFiles("${MAXFCT_DATA}" "${BEAGLE_OUTPUT_DIR}/bin/maxfct" false)
install(TARGETS maxfct DESTINATION bin/maxfct)
install(FILES ${MAXFCT_DATA} DESTINATION bin/maxfct)

#	# maxfctes example
#	file(GLOB MAXFCTES_SRC  "${CMAKE_CURRENT_SOURCE_DIR}/src/Beagle-Examples/maxfctes/*.cpp")
#	file(GLOB MAXFCTES_DATA "${CMAKE_CURRENT_SOURCE_DIR}/src/Beagle-Examples/maxfctes/*.conf" "${CMAKE_CURRENT_SOURCE_DIR}/src/Beagle-Examples/maxfctes/ReadMe.txt")
#	add_executable(maxfctes ${MAXFCTES_SRC})
#	add_dependencies(maxfctes Beagle-ES Beagle-EC Beagle-Core)
#	target_link_libraries(maxfctes Beagle-ES Beagle-EC Beagle-Core pacc)
#	set_target_properties(maxfctes PROPERTIES RUNTIME_OUTPUT_DIRECTORY "${BEAGLE_OUTPUT_DIR}/bin/maxfctes")
#	MoveConfigFiles("${MAXFCTES_DATA}" "${BEAGLE_OUTPUT_DIR}/bin/maxfctes" false)
#	install(TARGETS maxfctes DESTINATION bin/maxfctes)
#	install(FILES ${MAXFCTES_DATA} DESTINATION bin/maxfctes)

# maxfctfloat example
file(GLOB MAXFCTFLOAT_SRC  "${CMAKE_CURRENT_SOURCE_DIR}/src/Beagle-Examples/maxfctfloat/*.cpp")
file(GLOB MAXFCTFLOAT_DATA "${CMAKE_CURRENT_SOURCE_DIR}/src/Beagle-Examples/maxfctfloat/*.conf" "${CMAKE_CURRENT_SOURCE_DIR}/src/Beagle-Examples/maxfctfloat/ReadMe.txt")
add_executable(maxfctfloat ${MAXFCTFLOAT_SRC})
add_dependencies(maxfctfloat Beagle-CMA Beagle-FltVec Beagle-EC Beagle-Core)
target_link_libraries(maxfctfloat Beagle-CMA Beagle-FltVec Beagle-EC Beagle-Core pacc)
set_target_properties(maxfctfloat PROPERTIES RUNTIME_OUTPUT_DIRECTORY "${BEAGLE_OUTPUT_DIR}/bin/maxfctfloat")
MoveConfigFiles("${MAXFCTFLOAT_DATA}" "${BEAGLE_OUTPUT_DIR}/bin/maxfctfloat" false)
install(TARGETS maxfctfloat DESTINATION bin/maxfctfloat)
install(FILES ${MAXFCTFLOAT_DATA} DESTINATION bin/maxfctfloat)

# multiplexer example
file(GLOB MULTIPLEXER_SRC  "${CMAKE_CURRENT_SOURCE_DIR}/src/Beagle-Examples/multiplexer/*.cpp")
file(GLOB MULTIPLEXER_DATA "${CMAKE_CURRENT_SOURCE_DIR}/src/Beagle-Examples/multiplexer/*.conf" "${CMAKE_CURRENT_SOURCE_DIR}/src/Beagle-Examples/multiplexer/ReadMe.txt")
add_executable(multiplexer ${MULTIPLEXER_SRC})
add_dependencies(multiplexer Beagle-GP Beagle-EC Beagle-Core)
target_link_libraries(multiplexer Beagle-GP Beagle-EC Beagle-Core pacc)
set_target_properties(multiplexer PROPERTIES RUNTIME_OUTPUT_DIRECTORY "${BEAGLE_OUTPUT_DIR}/bin/multiplexer")
MoveConfigFiles("${MULTIPLEXER_DATA}" "${BEAGLE_OUTPUT_DIR}/bin/multiplexer" false)
install(TARGETS multiplexer DESTINATION bin/multiplexer)
install(FILES ${MULTIPLEXER_DATA} DESTINATION bin/multiplexer)

# onemax example
file(GLOB ONEMAX_SRC  "${CMAKE_CURRENT_SOURCE_DIR}/src/Beagle-Examples/onemax/*.cpp")
file(GLOB ONEMAX_DATA "${CMAKE_CURRENT_SOURCE_DIR}/src/Beagle-Examples/onemax/*.conf" "${CMAKE_CURRENT_SOURCE_DIR}/src/Beagle-Examples/onemax/ReadMe.txt")
add_executable(onemax ${ONEMAX_SRC})
add_dependencies(onemax Beagle-BitStr Beagle-EC Beagle-Core)
target_link_libraries(onemax Beagle-BitStr Beagle-EC Beagle-Core pacc)
set_target_properties(onemax PROPERTIES RUNTIME_OUTPUT_DIRECTORY "${BEAGLE_OUTPUT_DIR}/bin/onemax")
MoveConfigFiles("${ONEMAX_DATA}" "${BEAGLE_OUTPUT_DIR}/bin/onemax" false)
install(TARGETS onemax DESTINATION bin/onemax)
install(FILES ${ONEMAX_DATA} DESTINATION bin/onemax)

# parity example
set(PARITY_SRC "${CMAKE_CURRENT_SOURCE_DIR}/src/Beagle-Examples/parity/ParityEvalOp.cpp" "${CMAKE_CURRENT_SOURCE_DIR}/src/Beagle-Examples/parity/ParityMain.cpp")
set(PARITY_FAST_SRC "${CMAKE_CURRENT_SOURCE_DIR}/src/Beagle-Examples/parity/ParityFastEvalOp.cpp" "${CMAKE_CURRENT_SOURCE_DIR}/src/Beagle-Examples/parity/ParityFastMain.cpp")
file(GLOB PARITY_DATA "${CMAKE_CURRENT_SOURCE_DIR}/src/Beagle-Examples/parity/*.conf" "${CMAKE_CURRENT_SOURCE_DIR}/src/Beagle-Examples/parity/ReadMe.txt")
add_executable(parity ${PARITY_SRC})
add_dependencies(parity Beagle-STGP Beagle-GP Beagle-EC Beagle-Core)
target_link_libraries(parity Beagle-STGP Beagle-GP Beagle-EC Beagle-Core pacc)
add_executable(parity-fast ${PARITY_FAST_SRC})
add_dependencies(parity-fast Beagle-STGP Beagle-GP Beagle-EC Beagle-Core)
target_link_libraries(parity-fast Beagle-STGP Beagle-GP Beagle-EC Beagle-Core pacc)
set_target_properties(parity parity-fast PROPERTIES RUNTIME_OUTPUT_DIRECTORY "${BEAGLE_OUTPUT_DIR}/bin/parity")
MoveConfigFiles("${PARITY_DATA}" "${BEAGLE_OUTPUT_DIR}/bin/parity" false)
install(TARGETS parity parity-fast DESTINATION bin/parity)
install(FILES ${PARITY_DATA} DESTINATION bin/parity)

# spambase example
file(GLOB SPAMBASE_SRC  "${CMAKE_CURRENT_SOURCE_DIR}/src/Beagle-Examples/spambase/*.cpp")
file(GLOB SPAMBASE_DATA "${CMAKE_CURRENT_SOURCE_DIR}/src/Beagle-Examples/spambase/*.conf" "${CMAKE_CURRENT_SOURCE_DIR}/src/Beagle-Examples/spambase/spambase.data" "${CMAKE_CURRENT_SOURCE_DIR}/src/Beagle-Examples/spambase/ReadMe.txt")
add_executable(spambase ${SPAMBASE_SRC})
add_dependencies(spambase Beagle-STGP Beagle-GP Beagle-EC Beagle-Core)
target_link_libraries(spambase Beagle-STGP Beagle-GP Beagle-EC Beagle-Core pacc)
set_target_properties(spambase PROPERTIES RUNTIME_OUTPUT_DIRECTORY "${BEAGLE_OUTPUT_DIR}/bin/spambase")
MoveConfigFiles("${SPAMBASE_DATA}" "${BEAGLE_OUTPUT_DIR}/bin/spambase" false)
install(TARGETS spambase DESTINATION bin/spambase)
install(FILES ${SPAMBASE_DATA} DESTINATION bin/spambase)

# symbreg example
file(GLOB SYMBREG_SRC  "${CMAKE_CURRENT_SOURCE_DIR}/src/Beagle-Examples/symbreg/*.cpp")
file(GLOB SYMBREG_DATA "${CMAKE_CURRENT_SOURCE_DIR}/src/Beagle-Examples/symbreg/*.conf" "${CMAKE_CURRENT_SOURCE_DIR}/src/Beagle-Examples/symbreg/ReadMe.txt")
add_executable(symbreg ${SYMBREG_SRC})
add_dependencies(symbreg Beagle-STGP Beagle-GP Beagle-EC Beagle-Core)
target_link_libraries(symbreg Beagle-STGP Beagle-GP Beagle-EC Beagle-Core pacc)
set_target_properties(symbreg PROPERTIES RUNTIME_OUTPUT_DIRECTORY "${BEAGLE_OUTPUT_DIR}/bin/symbreg")
MoveConfigFiles("${SYMBREG_DATA}" "${BEAGLE_OUTPUT_DIR}/bin/symbreg" false)
install(TARGETS symbreg DESTINATION bin/symbreg)
install(FILES ${SYMBREG_DATA} DESTINATION bin/symbreg)

# tsp example
file(GLOB TSP_SRC  "${CMAKE_CURRENT_SOURCE_DIR}/src/Beagle-Examples/tsp/*.cpp")
file(GLOB TSP_DATA "${CMAKE_CURRENT_SOURCE_DIR}/src/Beagle-Examples/tsp/*.conf" "${CMAKE_CURRENT_SOURCE_DIR}/src/Beagle-Examples/tsp/ReadMe.txt")
add_executable(tsp ${TSP_SRC})
add_dependencies(tsp Beagle-IntVec Beagle-EC Beagle-Core)
target_link_libraries(tsp Beagle-IntVec Beagle-EC Beagle-Core pacc)
set_target_properties(tsp PROPERTIES RUNTIME_OUTPUT_DIRECTORY "${BEAGLE_OUTPUT_DIR}/bin/tsp")
MoveConfigFiles("${TSP_DATA}" "${BEAGLE_OUTPUT_DIR}/bin/tsp" false)
install(TARGETS tsp DESTINATION bin/tsp)
install(FILES ${TSP_DATA} DESTINATION bin/tsp)

# tsp-hpc example
if(NOT BEAGLE_NO_HPC)
    file(GLOB TSP_HPC_SRC  "${CMAKE_CURRENT_SOURCE_DIR}/src/Beagle-Examples/tsp-hpc/*.cpp")
    file(GLOB TSP_HPC_DATA "${CMAKE_CURRENT_SOURCE_DIR}/src/Beagle-Examples/tsp-hpc/*.conf")
    add_executable(tsp-hpc ${TSP_HPC_SRC})
    add_dependencies(tsp-hpc Beagle-HPC Beagle-IntVec Beagle-EC Beagle-Core)
    target_link_libraries(tsp-hpc Beagle-HPC Beagle-IntVec Beagle-EC Beagle-Core pacc)
    set_target_properties(tsp-hpc PROPERTIES RUNTIME_OUTPUT_DIRECTORY "${BEAGLE_OUTPUT_DIR}/bin/tsp-hpc")
    MoveConfigFiles("${TSP_HPC_DATA}" "${BEAGLE_OUTPUT_DIR}/bin/tsp-hpc" false)
    install(TARGETS tsp-hpc DESTINATION bin/tsp-hpc)
    install(FILES ${TSP_DATA} DESTINATION bin/tsp-hpc)
endif(NOT BEAGLE_NO_HPC)

# zeromin example
file(GLOB ZEROMIN_SRC  "${CMAKE_CURRENT_SOURCE_DIR}/src/Beagle-Examples/zeromin/*.cpp")
file(GLOB ZEROMIN_DATA "${CMAKE_CURRENT_SOURCE_DIR}/src/Beagle-Examples/zeromin/*.conf" "${CMAKE_CURRENT_SOURCE_DIR}/src/Beagle-Examples/zeromin/ReadMe.txt")
add_executable(zeromin ${ZEROMIN_SRC})
add_dependencies(zeromin Beagle-BitStr Beagle-EC Beagle-Core)
target_link_libraries(zeromin Beagle-BitStr Beagle-EC Beagle-Core pacc)
set_target_properties(zeromin PROPERTIES RUNTIME_OUTPUT_DIRECTORY "${BEAGLE_OUTPUT_DIR}/bin/zeromin")
MoveConfigFiles("${ZEROMIN_DATA}" "${BEAGLE_OUTPUT_DIR}/bin/zeromin" false)
install(TARGETS zeromin DESTINATION bin/zeromin)
install(FILES ${ZEROMIN_DATA} DESTINATION bin/zeromin)